update FilterPointsPie
fixed compilation error:
 - parenthesis in if statement,
 - max, min(startD, endD) changed to maxE, minE(startD, endD) to match types